### ISSUE TITLE
Sayfayı Yenileyince 404 Hatası

### ISSUE THREAD

**Issue by eyupfidan** [sabakukhyraa/agenda-react#1]
Sayfayı yenileyince veya aynı linki farklı bir sekmede açında 404 hatası almaktayım.

![back](https://user-images.githubusercontent.com/60450646/220553826-1efbc811-f65e-4af0-8af4-b85fdfcdaab2.png)

**Comment by sabakukhyraa** [comment]
Fixed, teşekkürler.

**Comment by sabakukhyraa** [comment]
Fixed, teşekkürler.
